name: coursedart
description: A sample command-line application.
version: 1.0.0+1
# homepage: https://www.example.com

environment:
   sdk: ^3.9.2

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  
dependencies:
  ffi: ^2.1.0
  json_annotation: ^4.9.0
  
